"""Base class for all unbox multiplugins."""

from typing import Callable

from azul_runner import BinaryPlugin, Feature, State

from ..unbox import box_base


class BaseUnbox:
    """Base class for all unbox multiplugins."""

    # Display name of the Unbox class to be used by the multiplugin.
    box_display_name: str
    # Name of the Unbox class to be used by the multiplugin used to get correct class from unbox.
    box_class: str
    # Description of the unbox action e.g extracted, unrar, unzipped or unpacked.
    box_action: str

    # Secondary box to use if the first one fails on a file.
    secondary_box_class: str | None = None

    # Allowed input data type for the unbox muliplugin.
    INPUT_DATA_TYPE: list[str]

    # Output features that can be generated by the mutliplugin.
    FEATURES: set[Feature] = []

    # Do the child artifacts generated by the multiplugin have a filename.
    children_have_useable_filenames: bool = True

    # NOTE - metatypes, key_metatypes and rel_metatypes are closely related they all get metadata from unbox
    # and convert it to a form for Azul. They are distinct because they are done at different times for different
    # objects (child vs parent metadata).

    # Tuples of box metadata to plugin feature mappings for features about/on the container.
    metatypes: list[tuple[str, str, Callable | None]] = []

    # list of conversions from unbox metadata to a feature value via an optional function. The metadata is stored
    # on the parent object to be a label feature where the labelled feature value is the unbox key.
    key_metatypes: list[tuple[str, str, Callable | None]] = []

    # Tuples of box key metadata to action name, to record in the child relationship.  These are
    # added as a string of of name=meta on the relationship.  eg. for PDF 'object_id=3'.
    rel_metatypes: list[tuple[str, str, Callable | None]] = []

    @classmethod
    def get_descriptive_box_display_name(cls, file_type: str):
        """Get the box display name.

        Args:
            file_type (str): param overridden by 7zip to pass more useful displayname.
        """
        return cls.box_display_name

    def exception_handler(self, ex: Exception, plugin_ref: BinaryPlugin) -> dict:
        """Is a default unbox exception handler to allow subclasses to override behaviour."""
        # NotSupported indicates that this box couldn't parse the entity for some reason
        if isinstance(ex, box_base.NotSupported):
            return State(State.Label.ERROR_EXCEPTION, message=str(ex))
        if isinstance(ex, box_base.PasswordError):
            # do entity errored jobs still get retried? as we may want to retry later
            # if dictionary is updated?
            return State(State.Label.ERROR_EXCEPTION, message=str(ex))
        if isinstance(ex, box_base.Corrupted):
            return State(State.Label.COMPLETED_WITH_ERRORS, message=str(ex))
        raise
